apiVersion: apps/v1
kind: Deployment
metadata:
  name: DockerSQLApp-deployment
  labels:
    app: DockerSQLApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DockerSQLApp
  template:
    metadata:
      labels:
        app: DockerSQLApp
    spec:
      containers:
      - name: DockerSQLAppServer
        image: 6032-89-205-126-202.ngrok.io/dockersqlcontainer:1.0.2
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: DockerSQLApp-service
spec:
  selector:
      app: DockerSQLApp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110


