apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockersqlapp-deployment
  namespace: kube-system
  labels:
    app: dockersqlapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dockersqlapp
      release: production
  template:
    metadata:
      labels:
        app: dockersqlapp
        release: production
    spec:
      containers:
      - name: dockersqlappserver
        image: 5a35-89-205-126-233.ngrok.io/dockersqlcontainer:1.1.18
        imagePullSecrets:
        - name: regcred2
        ports:
        - containerPort: 80


