apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockersqlapp-deployment
  namespace: kube-system
  labels:
    app: dockersqlapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dockersqlapp
  template:
    metadata:
      labels:
        app: dockersqlapp
    spec:
      containers:
      - name: dockersqlappserver
        image: 70b9-89-205-126-245.ngrok.io/dockersqlcontainer:1.1.4
        imagePullSecrets:
        - name: regcred1
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: dockersqlapp-service
spec:
  selector:
      app: dockersqlapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30163


