apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockersqlapp-deployment
  labels:
    app: dockersqlapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockersqlapp
  template:
    metadata:
      labels:
        app: dockersqlapp
    spec:
      containers:
      - name: dockersqlappserver
        image: 6032-89-205-126-202.ngrok.io/dockersqlcontainer:1.0.3
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: dockersqlapp-service
spec:
  selector:
      app: dockersqlapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110


