apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockersqlapp-deployment
  namespace: kube-system
  labels:
    app: dockersqlapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dockersqlapp
      release: production
  template:
    metadata:
      labels:
        app: dockersqlapp
        release: production
    spec:
      containers:
      - name: dockersqlappserver
        image: e837-89-205-126-202.ngrok.io/dockersqlcontainer:1.1.21
        imagePullSecrets:
        - name: regcred2
        ports:
        - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: dockersqlapp-service
  namespace: kube-system
  labels:
    app: dockersqlapp
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
      app: dockersqlapp
  type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
  namespace: kube-system
  labels:
    app: dockersqlapp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
      app: dockersqlapp
  type: ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: lb-service
  namespace: kube-system
  labels:
    app: dockersqlapp
spec:
  selector:
    app: dockersqlapp
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80

apiVersion: v1
kind: Service
metadata:
  name: my-xn-service
  namespace: kube-system
  labels:
    app: dockersqlapp
spec:
  type: ExternalName
  externalName: dockersqlappexternal.com
