apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockersqlapp-deployment
  labels:
    app: dockersqlapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dockersqlapp
  template:
    metadata:
      labels:
        app: dockersqlapp
    spec:
      containers:
      - name: dockersqlappserver
        image: 9968-89-205-126-233.ngrok.io/dockersqlcontainer:1.0.6
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: dockersqlapp-service
spec:
  selector:
      app: dockersqlapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30163


